version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: insa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - spring-net

  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - db
    networks:
      - spring-net

  service-produit:
    build:
      context: ./api/products/products
      dockerfile: Dockerfile
    container_name: service-produit
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/insa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - spring-net

  service-commande:
    build:
      context: ./api/orders/orders
      dockerfile: Dockerfile
    container_name: service-commande
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/insa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - spring-net

  service-client:
    build:
      context: ./api/users/users
      dockerfile: Dockerfile
    container_name: service-client
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/insa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - spring-net

  api-gateway:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - service-produit
      - service-commande
      - service-client
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - spring-net

  front:
    build:
      context: ./LaBelleCave_Front
      dockerfile: Dockerfile
    container_name: la-belle-cave-front
    ports:
      - "8050:8050"
    depends_on:
      - api-gateway # Dépend de l'API Gateway si votre front doit communiquer avec l'API
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
